project:
  type: website
  output-dir: docs
 
website:
  title: "SafeJOINTs"
  navbar:
    title: false
    logo: images/University_of_Essex_logo.svg.png 
    left:
      - href: index.qmd#about-the-project
        text: Home
      - href: about.qmd
        text: About the Team
      - href: breakingnews.qmd
        text: Breaking News
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: contact.html
        text: Contact
  favicon: img/favicon.ico

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css